### ISSUE TITLE
Publish package command doesn't publish anything

### ISSUE THREAD

**Issue by cristianuibar** [biscolab/laravel-recaptcha#20]
**Describe the bug**
Using this command: `php artisan vendor:publish --provider="Biscolab\ReCaptcha\ReCaptchaServiceProvider"` does not publish any files.

**To Reproduce**
Follow the install instructions and execute `php artisan vendor:publish --provider="Biscolab\ReCaptcha\ReCaptchaServiceProvider"`. Returned message is: `Publishing complete.` but nothing is published in config or anywhere else.

**Expected behavior**
At least the config file to be published.

**Environment:**
 - OS: Windows 10
 - PHP version 7.3.0
 - Laravel ^5.6

**Additional context**
Running locally under XAMPP v 3.2.2 using PHP 7.3.

**Comment by biscolab** [comment]
I can't replicate the same issue, but it does not seem to be a bug.
I suggest you try the following steps:
1. check `config` directory permissions in order to be able to write into that folder
2. if you don't use "auto-discover" service make sure to add `ReCaptchaServiceProvider` to `$providers` list in `config/app.php`
3. run `php artisan vendor:publish --provider="Biscolab\ReCaptcha\ReCaptchaServiceProvider"` command 

Please let me know, thanks!

**Comment by prodigy7** [comment]
Please fix your documentation with the quoted php artisan command! Thx!

**Comment by jacobkball** [comment]
I had the same issue. I was able to fix it by updating my composer.json to "biscolab/laravel-recaptcha": "^3.0", (for some reason, it only installed 3.0) and then ran composer update, which got the latest version and did an autoload dump. After that, I was able to successfully run the vendor publish command.
