### ISSUE TITLE
Using on sub folder

### ISSUE THREAD

**Issue by DAGATOAMM** [biscolab/laravel-recaptcha#31]
When de laravel is installed on subfolder the default_validation_route generate 404.

**To Reproduce**
1. install libraries and config all
2. When laravel is on subfolder the http://domain/subfolder/biscolab-recaptcha/validate?token=
generate 404

**Comment by biscolab** [comment]
Hi @DAGATOAMM, take a look at [Configuration file](https://laravel-recaptcha-docs.biscolab.com/docs/configuration#complete-configuration).
Since **v3.2.0** you can set your validation route, the default value is `biscolab-recaptcha/validate` but you can change that at your convenience. Did you set `default_validation_route`?
