### ISSUE TITLE
[Laravel 8] Implementing ReCaptcha inside JetstreamServiceProvider

### ISSUE THREAD

**Issue by american-it** [biscolab/laravel-recaptcha#50]
Hi mighty all,

Trying to inject the usual ReCaptcha (your packet) functionality into JetstreamServiceProvider.

[GIST](https://gist.github.com/american-it/30dc006584863fc20e514f92736893c6)

If the captcha is empty — everything is OK and I get an error, but if captcha is passed/checked I also get an error saying "You have to pass ReCaptcha check". Deep night now, please point me in the right direction.

P.S. All the same works for Jetstream while creating a new user (updated validator inside Fortify/CreateNewUser.php).

**Comment by biscolab** [comment]
Hi @american-it. Unfortunately, I don't have enough details about your issue to be able to recreate it. You should follow the [Bug report template](https://github.com/biscolab/laravel-recaptcha/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) to help me understand what could be happened...I don't know what JetStream stack you chose, by guessing you configured a **v2 checkbox reCAPTCHA** following provided [documentation](https://laravel-recaptcha-docs.biscolab.com/docs/how-to-use-v2#recaptcha-v2-checkbox) and perhaps either you made a configuration mistake or you duplicated `g-recaptcha-response` field (I repeat...By guessing!). It's the first time I see the error you reported and I don't know where it comes from because this package returns an error message you have to customize (if not, the only message you can see is `"validation.recaptcha"`).
So please check your local configuration and provide mi more details. Thanks
